### ISSUE TITLE
Use Chrome instead of PyBluez?

### ISSUE THREAD

**Issue by ajcord** [SIGMusic/tonal-lightfield#1]
Would it be better to use the Chrome Bluetooth API instead of Python to run the manager? We could have a Chrome extension installed that runs a content script in the simulation and provides a simple setRGB method. [developer.chrome.com](https://developer.chrome.com/apps/app_bluetooth)

This would both improve platform support by including OS X and Chrome OS as well as eliminating the need for a light socket.

@scowalt @jlakowski

**Comment by scowalt** [comment]
Only down-side is that its no longer cross-browser. However, this is acceptable considering our plans to run the exhibit on Chrome anyways. I think this is a great plan!

**Comment by ajcord** [comment]
I started working on a demo: [first commit](https://github.com/SIGMusic/tonal-lightfield/commit/e6453ebf8dd535daeb861dfd098d6c0fc27d7926)

Unfortunately, my laptop isn't recognizing my JY-MCU module, so I can't fully test it. I'll have to test on Sunday. But it does recognize all the lights I've previously connected.

One hurdle we need to overcome is how to communicate with the page via JS because I found out that Chrome apps can't use content scripts, only extensions. I'm looking into postMessage and similar HTML5 APIs.

**Comment by scowalt** [comment]
One option is to continue to use Websockets.

**Comment by ajcord** [comment]
I was able to get messaging working. I verified that it works from http://tonal-starfield.herokuapp.com, and the extension only has permission to receive messages from that domain.

See [here](https://github.com/SIGMusic/tonal-lightfield/blob/db585b2da8c81435aa083e4e7c7578e32bce1332/extension/background.js#L157) for a really simple example usage. The only thing you need is the extension ID, which may mean that the extension needs to be packaged so the ID isn't randomized. Not a problem though.

We may want to look into [connections](https://developer.chrome.com/apps/messaging#connect) instead of messages, which are more like sockets instead of one-time messages. However, it sounds to me like these are only possible from content scripts and not the webpage itself.

**Comment by scowalt** [comment]
Could you add localhost as a match for testing purposes? Looking forward to playing with this on Sunday!

**Comment by ajcord** [comment]
I can't test it since I don't have a local webserver, but I added it to the list of externally connectable hosts in the latest commit.

**Comment by scowalt** [comment]
So we can't use WebSockets for communication for this extension. We would need to run a WebSocket server, which isn't possible to do inside of a web browser.

Also, content scripts are only allowed in extensions, while the bluetooth module is only allowed in packaged apps. So using content scripts will not be an option

**Comment by ajcord** [comment]
I think we're going to try to stick with PyBluez because we got that working just now. The Chrome extension is acting weird.

**Comment by scowalt** [comment]
Thanks for the heads-up, I'll retreat from the Chrome Extension rabbit hole

**Comment by ajcord** [comment]
Closing issue for now. We can revisit this later if we so choose.
